theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
title: LetsHack
description: Write-Ups and Cyber Security News!
author: gl0wy
permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true
