theme: jekyll-theme-hacker
feed:
  path: https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml
title: LetsHack
description: Write-Ups and Cyber Security News!
author: gl0wy
permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true
